version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_ecommerce
    ports:
      - '6543:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
